aws_project_id            = ""
aws_region                = "ap-northeast-1"
owner                     = "beaver"
codecommit_repo_name      = "beaver-operators"
codecommit_branch         = "dev"
codebuild_project_name    = "beaver-operators"
codepipeline_project_name = "beaver-operators"
cloudwatch_stream_name    = "codebuild-beaver-operators"
